config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'
  get 'password_reset/edit'
  get '/login', to: 'sessions#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'users/new'
  get '/home',to: 'static_pages#home'
  get '/help',to:  'static_pages#help'

  get '/about',to:  'static_pages#about'
  get '/contact',to:  'static_pages#contact'
  get '/news',to:  'static_pages#news'
  get '/signup',  to: 'accounts#new'

  get '/password_reset', to: 'password_reset#new'

  #Test mailers
  get '/mailer', to: 'user_mailer#account_activation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :accounts do 
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :accounts
  resources :account_activations, only: [:edit]
  resources :password_reset, only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: {maximum: 5}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },uniqueness: {case_sensitive: false}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = Account.find(params[:id])
end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:notice] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    uEmail=user.email
    if uEmail.empty?
      uEmail="test@gmail.com"
    end
    gravatar_id = Digest::MD5::hexdigest(uEmail)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@accounts, url: signup_path) do |f| %>
    <%= render 'shared/error_message' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>