config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'
  get 'password_reset/edit'
  get '/login', to: 'sessions#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'users/new'
  get '/home',to: 'static_pages#home'
  get '/help',to:  'static_pages#help'

  get '/about',to:  'static_pages#about'
  get '/contact',to:  'static_pages#contact'
  get '/news',to:  'static_pages#news'
  get '/signup',  to: 'accounts#new'

  get '/password_reset', to: 'password_reset#new'

  #Test mailers
  get '/mailer', to: 'user_mailer#account_activation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :accounts do 
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :accounts
  resources :account_activations, only: [:edit]
  resources :password_reset, only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user? (@account) %>
  <div id="follow_form">
  <% if current_user.following? (@account) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_message', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <span class="picture">
    <table>
      <tr>
        <td><img id="picture_preview"/></td>
        <td><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', :onchange=>"readURL(this);"%></td>
      </tr>
    </table>
  </span>


  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>


<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
  // to make image preview before uploading file.
  function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
          $('#picture_preview')
              .attr('src', e.target.result)
              .width(100)
              .height(100);
        };

      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/shared/_stats.html.erb
<% @account ||= current_user %>
<div class="stats">
  <a href="<%= following_account_path(@account) %>">
    <strong id="following" class="stat">
      <%= @account.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_account_path(@account) %>">
    <strong id="followers" class="stat">
      <%= @account.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>