config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'
  get 'password_reset/edit'
  get '/login', to: 'sessions#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'users/new'
  get '/home',to: 'static_pages#home'
  get '/help',to:  'static_pages#help'

  get '/about',to:  'static_pages#about'
  get '/contact',to:  'static_pages#contact'
  get '/news',to:  'static_pages#news'
  get '/signup',  to: 'accounts#new'

  get '/password_reset', to: 'password_reset#new'

  #Test mailers
  get '/mailer', to: 'user_mailer#account_activation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :accounts do 
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :accounts
  resources :account_activations, only: [:edit]
  resources :password_reset, only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-fixed-bottom">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Contact", '/contact' %></li>
      <li><%= link_to "news", "http://www.google.com" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/home' %></li>
        <li><%= link_to "Help",  '/help' %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", "/accounts/" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to current_user.name, account_path(current_user) %></li>
              <li><%= link_to "Settings", edit_account_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", '/login' %></li>
        <li><%= link_to "Sign up", '/signup' %></li>
        <% end %>
      </ul>

    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<% provide(:title, "project") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/shim' %>
    <style type="text/css">
      .alert-success{
        color: green;
      }
      .alert-danger{
        color: red;
      }
    </style>

    <!-- to show image preview before submit button click -->
    <link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>